config/routes.rb
Rails.application.routes.draw do


  root 'page#index'

  get "login", to: "sessions#login"
  get "logout", to: "sessions#logout"

  resources :jobs
  resources :sessions
  resources :users
  get "success" => "page#success"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, :description, :contact, :company, :location, :email, :phone_number, presence: true
  after_create :post_to_slack

  self.per_page = 25

  def post_to_slack
    job = Job.find(self.id)

    base_url_dev = "<http://localhost:3000/jobs/#{self.id}>"
    base_url_prod = "<https://wynterque.herokuapp.com/jobs/#{self.id}"
    payload = { text: "Check out this job opportunity for a #{job.title} with #{job.company} in #{job.location}\n #{base_url_prod}", username: "wynterque" }

    # This is currently being directed to Shaun's test slack channel.
    response = HTTParty.post('https://hooks.slack.com/services/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', body: payload.to_json )
	end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  def self.find_for_session(session)
    u = find_or_create_by(ex_id: session["id"]) do |user|
      user.first_name = session["first_name"]
      user.last_name = session["last_name"]
    end

    session["role_name"] = session["role"]

    (session.keys-["id", "role"]).each do |key|
      value = session[key]
      u.singleton_class.class_eval { attr_accessor key }
      u.instance_variable_set("@#{key}".to_sym, value)
    end if u
    u
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action CASClient::Frameworks::Rails::Filter
  before_action :current_user
  helper_method :current_user
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_for_session(session[:cas_extra_attributes.to_s]) rescue nil
  end

  


  # def authorize
  #   redirect_to '/login' unless current_user
  # end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  skip_before_action CASClient::Frameworks::Rails::Filter, only: [:new, :create]
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.paginate(:page => params[:page])
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        # redirect_to url_for(:controller => :controller_name, :action => :action_name)
        format.html { redirect_to url_for(:controller => "page", :action => "success"), notice: 'Your open role was successfully created!' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :contact, :company, :location, :email, :phone_number, :email_shown, :phone_number_shown)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
skip_before_action CASClient::Frameworks::Rails::Filter, only: [:success]

  def index
  end

  def show
  end

  def new
  end

  def success
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login
    if @current_user
      redirect_to root_path
    end
  end

  def logout
    session[:ex_id] = nil
    session[:user_id] = nil
    CASClient::Frameworks::Rails::Filter.logout(self)
  end


  def forgot_password
    redirect_to "http://people.wyncode.co/forgot_password" and return
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        redirect_to '/signup'
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<%= form_for(job) do |f| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
  <div class="form-group">
    <%= f.text_field :title, placeholder: "Enter the Job Title", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.text_area :description, placeholder: "Enter the job description, copy and pasting is fine", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.text_field :company, placeholder: "Enter the company/organization name", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.text_field :location, placeholder: "Enter position location", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.text_field :contact, placeholder: "Enter email or preferred method of contact", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.text_field :email, placeholder: "Enter the best email to reach you at", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.text_field :phone_number, placeholder: "Enter the best phone number to reach you at", :class => "form-control input-medium bfh-phone"%>
  </div>

  <div class="checkbox text-muted">
    <%= f.check_box :email_shown %>
      <%= label_tag("I want my email to be displayed to applicants") %>
  </div>
  <div class="checkbox text-muted">
    <%= f.check_box :phone_number_shown %>
      <%= label_tag("I want my phone number to be displayed to applicants") %>
  </div>





  <%= f.submit "Submit", :class => "btn btn-primary pull-right"%>
  <!-- <%= link_to 'Back', jobs_path %> -->
</fieldset>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice" class="text-success"><%= notice %></p>

<h1 align="center">Job Postings</h1>

<table class="table table-striped table-hover" >
  <thead>
    <tr>
      <th>Title</th>
      <th>Company</th>
      <!-- <th>Contact</th> -->
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.title, job %></td>
        <td><%= job.company %></td>
        <!-- <td><%= job.contact %></td> -->
        <td><%= job.location %></td>
      </tr>
    <% end %>

  </tbody>

</table>
<div align="center"><%= will_paginate @jobs, :class => "pagination pagination-sm"%></div>
<br>

app/views/jobs/new.html.erb
<h1 align="center">Post your open role below</h1>

<%= render 'form', job: @job %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>


<!-- <p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @job.contact %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Location:</strong>
  <%= @job.location %>
</p> -->


<div id="show_pad">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @job.title %></h3>
  </div>
  <div class="panel-body">

    <p>
      <strong>Company: </strong>
      <%= @job.company %> - <%= @job.location %>
    </p>
    <br>

    <p style="white-space: pre-wrap;">
      <%= @job.description %>
    </p>
    <br>

    <div class="well well-sm">
    <p>
      <strong>Contact:</strong>
      <%= @job.contact %>
    </p>
  </div>


<% if @job.email_shown %>
  <div class="well well-sm">
  <p>
    <strong>Email: </strong>
    <%= @job.email %>
  </p>
</div>
<% end %>

<% if @job.phone_number_shown %>
<div class="well well-sm">
  <p>
    <strong>Phone Number: </strong>
    <%= @job.phone_number %>
  </p>
</div>
<% end %>


  </div>
</div>




<%= link_to 'Back', jobs_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Wynterque</title>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <a style="background-image: <%= image_url "assets/images/logo.jpg" %>; width: 84px; height: 62px;" class="navbar-brand" href="/"></a> -->
          <a style="background-image" id="logothing" class="navbar-brand pull-left" href="/" ><%= image_tag("logo.jpg", :size => "116x76")  %></a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <!-- <a class=navbar-brand> <img src="<%= image_url('logo.jpg') %>" /> </a> -->
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", :controller => "page", :action => "index"%> </li>
          </ul>
           <ul class="nav navbar-nav">
             <li><%= link_to "Job Listings", :controller => "jobs", :action => "index"%> </li>
           </ul>
           <ul class="nav navbar-nav">
             <li><%= link_to "Post a Job", :controller => "jobs", :action => "new"%> </li>
           </ul>

           <ul class="nav navbar-nav navbar-right">
             <% if @current_user %>
                 <li>
                 <%= link_to "Log out", :controller => "sessions", :action => "logout" %>
                 </li>
             <% else %>
               <li>
                 <!-- logout isn't properly logging out  -->
                 <%= link_to("Login", CASClient::Frameworks::Rails::Filter.login_url(controller)) %>
               </li>
               <% end %>
             </ul>
          
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/page/index.html.erb
<div class="jumbotron">
  <h1>Welcome!</h1>
  <p>Click on "Job Listings" above to view all job postings. </p>
</div>

app/views/page/success.html.erb
<p class="text-success" align="center" id="notice"><%= notice %></p>

<h1 align="center">Thank you</h1>


<div align="center" id="anotherone">
<!-- # <%= link_to "Post another open role", :controller => "jobs", :action => "new", :class => "btn btn-primary"%> -->
<a class="btn btn-primary" <%= link_to "Post another open role", :controller => "jobs", :action => "new"%>

</div>

app/views/users/_form.html.erb
<%= form_for(user), :html => {:class => "form-horizontal"}, do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
  <div class="form-group">
    <%= f.label :first_name, :class => "control-label" %>
    <%= f.text_field :first_name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name, :class => "control-label" %>
    <%= f.text_field :last_name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name, :class => "control-label" %>
    <%= f.text_field :last_name, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
</fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Employer Sign Up</h1>

<%= form_for :user, url: '/users' do |f| %>

<div class="form-group">
  <%= f.text_field :first_name, placeholder: "First Name", :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.text_field :last_name, placeholder: "Last Name", :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.text_field :email, placeholder: "Email Address", :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.text_field :password, placeholder: "Password", :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.text_field :password_confirmation, placeholder: "Password Confirmation", :class => "form-control" %>
</div>

  <%= f.submit "Submit", :class => "btn btn-primary" %>

<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>